<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class M_item extends CI_Model
{

    public $table = 'item';
    public $id = 'id_item';
    public $order = 'DESC';
    public $protocolo = 'id_requisicao';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    

     function get_por_protocolo($id)
    {
        $this->db->where($this->protocolo, $id);
        return $this->db->get($this->table)->result();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_item', $q);
	$this->db->or_like('id_requisicao', $q);
	$this->db->or_like('descricao', $q);
	$this->db->or_like('valor', $q);
	$this->db->or_like('desconto', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_item', $q);
	$this->db->or_like('id_requisicao', $q);
	$this->db->or_like('descricao', $q);
	$this->db->or_like('valor', $q);
	$this->db->or_like('desconto', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Item_model.php */
/* Location: ./application/models/Item_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-04 18:57:53 */
/* http://harviacode.com */